import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderMenu from "@/components/Header"; // ✅ Importing Header
import Footer from "@/components/Footer"; // ✅ Importing Footer

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* ✅ Add HeaderMenu at the top */}
        <HeaderMenu />

        <main>{children}</main>

        {/* ✅ Add Footer at the bottom */}
        <Footer />
      </body>
    </html>
  );
}
